# assigns the custom role (traefik-ingress-controller) that was created in the 'traefik-cluster-role.yaml' file to
#   the service account (traefik-ingress-controller) created in the 'traefik-service-account.yaml' file.
# roleref - the ClusterRole
# subjects - the ServiceAccount

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: traefik-ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-ingress-controller
subjects:
  - kind: ServiceAccount
    name: traefik-ingress-controller
    namespace: default